openapi: 3.0.0
info:
    title: Jobs-API
    contact: {}
    version: "1.0"
servers:
    - url: https://jobs-api-expressjs-4lcx.onrender.com/api/v1
      variables: {}
paths:
    /auth/login:
        post:
            tags:
                - Auth
            summary: login
            operationId: login
            parameters: []
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/loginrequest"
                                - example:
                                      email: ishan00@gmail.com
                                      password: newPassword
                        example:
                            email: ishan00@gmail.com
                            password: newPassword
                required: true
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security: []
    /auth/register:
        post:
            tags:
                - Auth
            summary: register
            operationId: register
            parameters: []
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/registerrequest"
                                - example:
                                      name: ishan
                                      email: ishan00@gmail.com
                                      password: newPassword
                        example:
                            name: ishan
                            email: ishan00@gmail.com
                            password: newPassword
                required: true
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security: []
    /jobs:
        post:
            tags:
                - Jobs
            summary: Create Jobs
            operationId: CreateJobs
            parameters: []
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/CreateJobsRequest"
                                - example:
                                      company: Empty
                                      position: Dev Lead
                                      status: interview
                        example:
                            company: Empty
                            position: Dev Lead
                            status: interview
                required: true
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        get:
            tags:
                - Jobs
            summary: get All jobs
            operationId: getAlljobs
            parameters: []
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
    /jobs/{id}:
        parameters:
            - in: path
              name: id
              schema:
                  type: string
              required: true
              description: The jobs ID
        get:
            tags:
                - Jobs
            summary: user job
            operationId: userjob
            parameters: []
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        patch:
            tags:
                - Jobs
            summary: Update Job
            operationId: UpdateJob
            parameters: []
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/UpdateJobRequest"
                                - example:
                                      position: Changed
                                      company: changed
                        example:
                            position: Changed
                            company: changed
                required: true
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        delete:
            tags:
                - Jobs
            summary: delete jobs
            operationId: deletejobs
            parameters: []
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
components:
    schemas:
        loginrequest:
            title: loginrequest
            required:
                - email
                - password
            type: object
            properties:
                email:
                    type: string
                password:
                    type: string
            example:
                email: ishan00@gmail.com
                password: newPassword
        registerrequest:
            title: registerrequest
            required:
                - name
                - email
                - password
            type: object
            properties:
                name:
                    type: string
                email:
                    type: string
                password:
                    type: string
            example:
                name: ishan
                email: ishan00@gmail.com
                password: newPassword
        CreateJobsRequest:
            title: CreateJobsRequest
            required:
                - company
                - position
                - status
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
                status:
                    type: string
            example:
                company: Empty
                position: Dev Lead
                status: interview
        UpdateJobRequest:
            title: UpdateJobRequest
            required:
                - position
                - company
            type: object
            properties:
                position:
                    type: string
                company:
                    type: string
            example:
                position: Changed
                company: changed
    securitySchemes:
        bearer:
            type: http
            scheme: bearer
security: []
tags:
    - name: Misc
      description: ""
    - name: Auth
      description: ""
    - name: Jobs
      description: ""
